### ISSUE TITLE
react 16 support

### ISSUE THREAD

**Issue by didi0613** [jesusoterogomez/react-notify-toast#52]
Hello, can i know whats the plan of upgrading to react 16?
Thank you

**Comment by jesusoterogomez** [comment]
I still haven't thought about this, since my projects are using react 15. I will update the main project I'm working on to 16 in the near future, but I still haven't given the upgrade guide a deep look.

If I update this module to react 16, can it be backwards compatible? or would I have to possibly keep two versions of this module if I want to keep compatibility with react 15?

**Comment by didi0613** [comment]
@jesusoterogomez Yes it is. thanks!
